GET http://localhost:3000/

###

GET http://localhost:3000/dados


### 
POST http://localhost:3000/dados
Content-type: application/json

{
    "atividade": "teste",
    "materia": "cálculo",
    "data": "2023-04-25"
}

###

DELETE http://localhost:3000/dados?id=1